apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ah38iq9ls-nodejs
  janus-idp.io/tekton: ah38iq9ls-nodejs
  backstage.io/kubernetes-id: ah38iq9ls-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ah38iq9ls-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
